services:
  
  redis:
    env_file:
      - ./.env
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    command: /bin/sh -c "redis-server --requirepass $${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    networks:
      - ondc

  api:
    container_name: b2b-ondc-mock-api
    image: ghcr.io/abhijeetondc/b2b-ondc-mock-server-dev-backend:${IMAGE_TAG}
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - redis
    networks:
      - ondc

  web:
    container_name: b2b-ondc-mock-web
    image: ghcr.io/abhijeetondc/b2b-ondc-mock-server-dev-frontend:${IMAGE_TAG}
    env_file:
      - ./.env
    ports:
      - "8080:80"
    restart: always
    networks:
      - ondc
networks:
  ondc:
